apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
  namespace: gb001
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/guobingithub/KubeVela-GitOps-Infra-Demo
      ## secretRef: git-secret
      pullInterval: 1m
      git:
        branch: main
      path: ./apps