apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra
  namespace: gb002
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/guobingithub/KubeVela-GitOps-Infra-Demo
      ## secretRef: git-secret
      pullInterval: 2m
      git:
        branch: for-developers
      path: ./infrastructure
